@extends('layouts.mms')

@section('title', $bill->exists ? 'Edit Tagihan' : 'Input Tagihan Supplier')

@section('content')
@php($isEdit = $bill->exists)
<form method="POST" action="{{ $isEdit ? route('finance.ap.update', $bill) : route('finance.ap.store') }}">
@csrf @if($isEdit) @method('PUT') @endif
<div class="row"><div class="col-md-4"><div class="card shadow-sm mb-3"><div class="card-header bg-primary text-white">Info Tagihan</div><div class="card-body">
<div class="mb-2"><label>No. Bill (Internal)</label><input type="text" class="form-control fw-bold" value="{{ $bill->bill_number }}" readonly></div>
<div class="mb-2"><label>No. Invoice Supplier <span class="text-danger">*</span></label><input type="text" name="supplier_inv_number" class="form-control" value="{{ old('supplier_inv_number', $bill->supplier_inv_number) }}" required></div>
<div class="mb-2"><label>Ref. PO</label><select name="purchase_order_id" class="form-select" onchange="window.location.href='{{ route('finance.ap.create') }}?po_id='+this.value" @disabled($isEdit)><option value="">-- Pilih PO --</option>@foreach($purchaseOrders as $po)<option value="{{ $po->id }}" @selected((int) old('purchase_order_id', $purchaseOrder?->id ?: $bill->purchase_order_id) === $po->id)>{{ $po->po_number }} - {{ $po->supplier?->name }}</option>@endforeach</select>@if($isEdit)<input type="hidden" name="purchase_order_id" value="{{ $bill->purchase_order_id }}">@endif</div>
<div class="mb-2"><label>Supplier</label><select name="supplier_id" class="form-select" required><option value="">-- Pilih --</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected((int) old('supplier_id', $bill->supplier_id) === $supplier->id)>{{ $supplier->name }}</option>@endforeach</select></div>
</div></div></div><div class="col-md-8"><div class="card shadow-sm mb-3"><div class="card-header bg-light">Detail & Tanggal</div><div class="card-body"><div class="row"><div class="col-6 mb-3"><label>Tanggal Tagihan</label><input type="date" name="bill_date" class="form-control" value="{{ old('bill_date', optional($bill->bill_date)->format('Y-m-d') ?: now()->toDateString()) }}" required></div><div class="col-6 mb-3"><label>Jatuh Tempo</label><input type="date" name="due_date" class="form-control" value="{{ old('due_date', optional($bill->due_date)->format('Y-m-d') ?: now()->addDays(30)->toDateString()) }}" required></div></div><div class="mb-2"><label>Catatan</label><textarea name="notes" class="form-control" rows="2">{{ old('notes', $bill->notes) }}</textarea></div></div></div></div></div>
<div class="card shadow-sm mb-4"><div class="card-body p-0"><table class="table table-bordered mb-0"><thead class="bg-light"><tr><th>Barang</th><th width="10%">Qty</th><th width="20%">Harga</th><th width="20%">Subtotal</th></tr></thead><tbody>
@forelse($lines as $line)<tr><td>{{ $line['item_name'] }} ({{ $line['item_code'] }})<input type="hidden" name="item_id[]" value="{{ $line['item_id'] }}"></td><td><input type="number" name="qty[]" class="form-control text-center" value="{{ $line['qty'] + 0 }}" step="0.01" required></td><td><input type="number" name="price[]" class="form-control text-end" value="{{ $line['unit_price'] + 0 }}" step="0.01" required></td><td><input type="text" class="form-control text-end bg-light" value="{{ number_format($line['subtotal'], 0, ',', '.') }}" readonly></td></tr>@empty<tr><td colspan="4" class="text-center py-4 text-muted">Pilih PO untuk memuat item...</td></tr>@endforelse
</tbody><tfoot><tr><td colspan="3" class="text-end">Subtotal :</td><td class="text-end fw-bold">Rp {{ number_format($totals['subtotal'], 0, ',', '.') }}</td></tr><tr><td colspan="3" class="text-end align-middle">Diskon (Rp) :</td><td><input type="text" name="discount_amount" class="form-control text-end" value="{{ old('discount_amount', number_format($totals['discount'], 0, ',', '.')) }}"></td></tr><tr><td colspan="3" class="text-end align-middle">PPN (%) : <input type="number" name="ppn_percent" value="{{ old('ppn_percent', $purchaseOrder?->ppn_percent ?? 11) }}" style="width:70px"></td><td class="text-end">Rp {{ number_format($totals['tax'], 0, ',', '.') }}</td></tr><tr class="bg-light"><td colspan="3" class="text-end fw-bold">GRAND TOTAL :</td><td class="text-end fw-bold fs-5">Rp {{ number_format($totals['grand'], 0, ',', '.') }}</td></tr></tfoot></table></div></div>
<div class="d-flex justify-content-between mb-5"><a href="{{ route('finance.ap.index') }}" class="btn btn-secondary">Kembali</a><button type="submit" class="btn btn-primary btn-lg" @disabled($lines->isEmpty())>Simpan Tagihan</button></div>
</form>
@endsection
