@extends('layouts.mms')

@section('title', 'Input Pembayaran Hutang')

@section('content')
@php($remaining = $bill->grand_total - $bill->paid_amount)
<div class="row justify-content-center"><div class="col-md-8"><div class="card shadow-sm mb-4"><div class="card-header bg-dark text-white"><h5 class="mb-0">Informasi Tagihan</h5></div><div class="card-body"><div class="row"><div class="col-md-6"><table class="table table-sm table-borderless"><tr><td width="120" class="text-muted">No. Bill</td><td class="fw-bold">{{ $bill->bill_number }}</td></tr><tr><td class="text-muted">Inv Supplier</td><td>{{ $bill->supplier_inv_number }}</td></tr><tr><td class="text-muted">Supplier</td><td>{{ $bill->supplier?->name }}</td></tr></table></div><div class="col-md-6 text-end"><small class="text-muted">Total Tagihan</small><h4 class="fw-bold">Rp {{ number_format($bill->grand_total, 0, ',', '.') }}</h4><small class="text-muted">Sudah Dibayar</small><h5 class="text-success">Rp {{ number_format($bill->paid_amount, 0, ',', '.') }}</h5><hr><small class="text-muted">Sisa Tagihan</small><h3 class="text-danger fw-bold">Rp {{ number_format($remaining, 0, ',', '.') }}</h3></div></div></div></div>
<div class="card shadow mb-4"><div class="card-header bg-success text-white"><h6 class="mb-0 fw-bold">Form Pembayaran</h6></div><div class="card-body"><form method="POST" action="{{ route('finance.ap.payment.store', $bill) }}">@csrf<div class="row"><div class="col-md-6 mb-3"><label>Tanggal Bayar</label><input type="date" name="payment_date" class="form-control" value="{{ old('payment_date', now()->toDateString()) }}" required></div><div class="col-md-6 mb-3"><label>Metode Pembayaran</label><select name="method" class="form-select" required><option>Transfer Bank</option><option>Cash</option><option>Cek / Giro</option></select></div></div><div class="mb-3"><label>Jumlah Pembayaran (Rp)</label><input type="text" name="amount" class="form-control form-control-lg fw-bold text-success" value="{{ old('amount', number_format($remaining, 0, ',', '.')) }}" required><div class="form-text">Maksimal: Rp {{ number_format($remaining, 0, ',', '.') }}</div></div><div class="mb-3"><label>Catatan</label><textarea name="notes" class="form-control" rows="2">{{ old('notes') }}</textarea></div><div class="d-flex justify-content-between"><a href="{{ route('finance.ap.index') }}" class="btn btn-secondary">Batal</a><button type="submit" class="btn btn-success px-4 fw-bold">Simpan Pembayaran</button></div></form></div></div>
<div class="card shadow-sm"><div class="card-header bg-light"><h6 class="mb-0">Riwayat Pembayaran</h6></div><div class="card-body p-0"><table class="table table-striped mb-0"><thead class="table-light"><tr><th>Tanggal</th><th>Metode</th><th>Catatan</th><th class="text-end">Jumlah</th></tr></thead><tbody>@forelse($bill->payments as $payment)<tr><td>{{ optional($payment->payment_date)->format('d/m/Y') }}</td><td>{{ $payment->method }}</td><td>{{ $payment->notes ?: '-' }}</td><td class="text-end fw-bold">Rp {{ number_format($payment->amount, 0, ',', '.') }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-3">Belum ada pembayaran.</td></tr>@endforelse</tbody></table></div></div>
</div></div>
@endsection
